football/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from rest_framework import routers 
from footballweb.views import UserView, FootballView, wysylka_mail
from django.contrib.auth.views import (PasswordResetView, PasswordChangeDoneView, PasswordResetConfirmView, PasswordResetCompleteView)



router = routers.DefaultRouter() 
router.register(r'users', UserView)
router.register(r'football', FootballView)


urlpatterns = [
    path("admin/", admin.site.urls),
    path('football/', include('footballweb.urls')),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),    
    path('register/', wysylka_mail, name="register"),    
    path('password_reset', PasswordResetView.as_view(), name='password_reset'),    
    path('password_reset_done', PasswordChangeDoneView.as_view(), name='password_reset_done'),    
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),    
    path('password_reset_complete', PasswordResetCompleteView.as_view(), name='password_reset_complete'),    
    path('', include(router.urls))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



footballweb/urls.py
from django.urls import path
from footballweb.views import wszystkie_football, nowy_fc, edytuj_fc, usun_fc, contact
from . import views

urlpatterns = [
    path('wszystkie/', wszystkie_football, name="wszystkie_football"),
    path('nowy/', nowy_fc, name="nowy_fc"),
    path('edytuj/<int:id>/', edytuj_fc, name="edytuj_fc"),
    path('usun/<int:id>/', usun_fc, name="usun_fc"),
    path('contact/', contact, name="contact"),    
    path('wyszukiwarka/', views.wyszukiwarka, name='wyszukiwarka'),
    path('register/', views.register, name='register')
    
]

footballweb/models.py
from django.db import models
from .managers import FootballManager

from django.db.models.query import QuerySet



class Kraj():
        NIEZNANY = 6
        HISZPANIA = 0
        ANGLIA = 1
        WŁOCHY = 2
        NIEMCY = 3
        FRANCJA = 4
        POLSKA = 5
        KRAJE = (
            (HISZPANIA, 'Hiszpania'),
            (ANGLIA, 'Anglia'),
            (WŁOCHY, 'Włochy'),
            (NIEMCY, 'Niemcy'),
            (FRANCJA, 'Francja'),
            (POLSKA, 'Polska'),
            (NIEZNANY, 'Nieznany')
        )




class Football(models.Model):
    tytul = models.CharField(max_length=64, blank=False, unique=True)
    rok = models.PositiveSmallIntegerField(default=1900) 
    opis = models.TextField(default="")
    lig_mistrzów = models.PositiveSmallIntegerField(default=0, blank=True)
    logo = models.ImageField(upload_to="logosy", null=True, blank=True)
    kraj = models.PositiveSmallIntegerField(default=6, choices=Kraj.KRAJE)

    objects = models.Manager()
    kraje = FootballManager()


    def __str__(self):
        return self.tytul_z_rokiem()
    
    def tytul_z_rokiem(self):
        return "{} ({})".format(self.tytul, self.rok)






footballweb/forms.py
from django.forms import ModelForm 
from .models import Football
from django import forms
from django.contrib.auth.forms import UserCreationForm

class FcForm(ModelForm):
    class Meta:
        model = Football
        fields = ['tytul', 'opis', 'rok', 'lig_mistrzów', 'logo', 'kraj']


class WyszukiwarkaForm(forms.Form):
    KRAJE = (
        ('', 'Wybierz...'),
        # ('wszystkie', 'Pokaż wszystkie wyniki'),
        (0, 'Hiszpania'),
        (1, 'Anglia'),
        (2, 'Włochy'),
        (3, 'Niemcy'),
        (4, 'Francja'),
        (5, 'Polska'),
        (6, 'Nieznany'),
    )

    kraj = forms.ChoiceField(choices=KRAJE, required=False)



footballweb/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Football
from .forms import FcForm, WyszukiwarkaForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from rest_framework import viewsets
from django.contrib.auth.models import User 
from .serializers import UserSerializer, FootballSerializer
from django import forms
from django.http import HttpResponse
from django.core.mail import send_mail


class UserView(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class FootballView(viewsets.ModelViewSet):
    queryset = Football.objects.all()
    serializer_class = FootballSerializer


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


def wszystkie_football(request):
    # return HttpResponse("<h1>To jest nasz pierwszy test</h1>")
    wszystkie = Football.objects.all()
    # wszystkie = []
    return render(request, 'football.html', {'football': wszystkie})

def content(request):
    return render(request, 'content.html', {'content': content})

@login_required
def nowy_fc(request):

    form_fc = FcForm(request.POST or None, request.FILES or None)    

    if form_fc.is_valid():
        ball = form_fc.save(commit=False)
        ball.save() 

        return redirect(wyszukiwarka)

    return render(request, 'fc_form.html', {'form': form_fc, 'nowy': True}) 

@login_required
def edytuj_fc(request, id):

    football = get_object_or_404(Football, pk=id)  


    form_fc = FcForm(request.POST or None, request.FILES or None, instance=football)    

    if form_fc.is_valid():
        ball = form_fc.save(commit=False)

        ball.save() 

        return redirect(wyszukiwarka)

    return render(request, 'fc_form.html', {'form': form_fc,  'nowy': False}) 

@login_required
def usun_fc(request, id):
    football = get_object_or_404(Football, pk=id)

    if request.method == "POST":
        football.delete()
        return redirect(wszystkie_football)


    return render(request, 'potwierdz.html', {'football': football}) 



def wyszukiwarka(request):
    kluby = Football.objects.all()
    form = WyszukiwarkaForm(request.GET)

    if form.is_valid():
        kraj = form.cleaned_data['kraj']
        if kraj and kraj != 'wszystkie':
            kluby = kluby.filter(kraj=kraj)

    return render(request, 'wyszukiwarka.html', {'kluby': kluby, 'form': form})



def contact(request):

    return render(request, 'contact.html')



def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Logowanie użytkownika po rejestracji
            login(request, user)
            return redirect('wszystkie_football')  # Przekieruj użytkownika na stronę główną po rejestracji
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


def wysylka_mail(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # Wysłanie wiadomości powitalnej na adres e-mail
            email = form.cleaned_data['email']
            wiadomosc = "Witamy na naszej stronie InstaFootball. Cieszymy się, że jesteś z nami."
            send_mail(
                "Tutaj InstaFootball :)",
                wiadomosc,
                'adamrybinski.kontakt@gmail.com',
                [email],
                fail_silently=False
            )
            # ... kod do wysłania wiadomości e-mail ...
            return redirect('wszystkie_football')  # Przekierowanie po udanej rejestracji
    else:
        form = CustomUserCreationForm()
    
    return render(request, 'registration/register.html', {'form': form})

templates/contact.html
{% extends "glowny.html" %}

{% block strona %}

<header class="hero-img">
    <br>
    <br>
    <br>
    <br>
    <br>
    <section id="contact" class="contact py-5 choice">

        <h2 class="section-title">kontakt</h2>
        <div class="underLine"></div>

        <div class="container">

            <div class="row text-center contact-us">

                <div class="col-sm-6 col-lg-4 contact-item order-1">
                    <h3>Główna siedziba</h3>
                    <p>Rzeszów</p>
                    <p>al. Powstańców Warszawy 42/2</p>
                </div>

                <div class="col-lg-4 order-0 order-lg-1 contact-item">
                    <h3>social media</h3>
                    <div class="social-media">
                        <a href="https://www.facebook.com/adam.rybinski.25/"><i class="fab fa-facebook-f"></i></a>
                        <a href="https://www.instagram.com/rybinski_adam/"><i class="fa-brands fa-instagram"></i></a>
                        <a href="https://github.com/rybinski92"><i class="fa-brands fa-github"></i></a>
                    </div>
                </div>

                <div class="col-sm-6 col-lg-4 contact-item order-1">
                    <h3>Kontakt</h3>
                    <p><i class="fa-solid fa-phone"></i> 665 329 116</p>
                    <p><i class="fa-regular fa-envelope"></i> adamrybinski.kontakt@gmail.com</p>
                </div>

            </div>

        </div>
        <div class="contact-shadow"></div>

    </section>
    <div class="hero-shadow"></div>


</header>
<footer class="bg-dark text-light py-4 text-center">

    <p class="mb-0">&copy; 2023 | Runners</p>

</footer>



{% endblock %}

templates/email_form.html
<form method="POST">
    {% csrf_token %}
    <input type="email" name="email">
    <input type="submit" value="Wyślij">
</form>

templates/fc_form.html
{% extends 'glowny.html' %}
{% load bootstrap %}
{% block tytul %} FC form {% endblock %}


{% block strona %}


<header class="hero-img">
    <br>
    <br>
    <br>
    <br>
    <div class="card" style="width: 32rem;">
        <div class="card-body">
            <h5 class="card-title">Zaloguj się</h5>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}

                {% if nowy %}
                <button type="submit" class="btn btn-primary">Dodaj</button>
                {% else %}
                <button type="submit" class="btn btn-primary">Zapisz zmiany</button>
                {% endif %}
            </form>
        </div>
        <a href="{% url 'wszystkie_football' %}">Cofnij</a>
    </div>
    
    <div class="hero-shadow"></div>   
</header>
{% endblock %}

templates/football.html
{% extends 'glowny.html' %}

{% block tytul %} InstaFootball {% endblock %}


{% block strona %}
{% include "menu.html" %}


<div class="main-page">
    <header class="hero-img">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <div class="hero-text text-center p-2">
            <h1>witajcie w <i class="fa-solid fa-person-running"></i><i class="fa-solid fa-futbol"></i> insta<span class="blue-text">football</span></h1>
            <p>W miejscu, w którym możesz zobaczyć najlepsze kluby z europy oraz z Polski. <br> Zalogowani użytkownicy mogą
                dodawać oraz edytować kluby.</p>
            <a href="{% url 'wyszukiwarka' %}" class="btn btn-outline-light mt-2 text-uppercase">Zobacz kluby</a>
        </div>
        <div class="hero-shadow"></div>   
    </header>
</div>

{% endblock %}




templates/glowny.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>{% block tytul %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'nowy.css' %}">
    <script src="https://kit.fontawesome.com/207bcfd901.js" crossorigin="anonymous"></script>
</head>

<body>
    {% include "menu.html" %}

    {% block strona %} {% endblock %}
    
</body>

</html>

templates/menu.html



  <nav class="navbar navbar-expand-lg position-fixed top-0 w-100 py-3" id="navId">
    <div class="container">
      <a class="navbar-brand" href="{% url 'wszystkie_football' %}"><i class="fa-solid fa-person-running"></i><i class="fa-solid fa-futbol"></i> insta<span
          class="blue-text">football</span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa-solid fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto">   
           
   
            <a href="{% url 'nowy_fc' %}"><button type="button" class="btn btn-success">Dodaj klub <i class="fa-solid fa-square-plus"></i></button></a>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'wszystkie_football' %}">strona główna</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'wyszukiwarka' %}">Baza klubów</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Kontakt</a>
            </li>

            
            {% if user.is_authenticated %}         
            <a href="{% url 'logout' %}"><button type="button" class="btn btn-dark">Logout {{ user.username }} <i class="fa-solid fa-right-from-bracket"></i></button></a>
            {% else %}
            <a href="{% url 'register' %}"><button type="button" class="btn btn-success">Załóż konto</button></a>
            <a href="{% url 'login' %}"><button type="button" class="btn btn-primary">Login</button></a>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </nav>

templates/potwierdz.html
{% extends 'glowny.html' %}
<!-- {% load bootstrap %} -->

{% block tytul %} Accept {% endblock %}


{% block strona %}
<header class="hero-img">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="card" style="width: 32rem;">
        <div class="card-body">
            <h5 class="card-title">Czy chcesz usunąć: "{{ football.tytul }}"?</h5>

            <form method="POST">
                {% csrf_token %}
            
                <button type="submit" class="btn btn-danger">Usuń FC</button>
            </form>
            <a href="{% url 'wyszukiwarka' %}">Cofnij</a>
        </div>
    </div>
    <div class="hero-shadow"></div>   
</header>
{% endblock %}

templates/wyszukiwarka.html
{% extends 'glowny.html' %}

{% block tytul %} Lista FC {% endblock %}


{% block strona %}
{% include "menu.html" %}


<header class="hero-img">
<br>
<br>
<br>
    
    <div class="center-form">        
        <br>
        <form method="get" class="form-inline">
            <h1>Wyszukiwarka klubów</h1>
            <div class="input-group">
                <label for="{{ form.kraj.id_for_label }}" class="input-group-text">Wybierz kraj</label>
                {{ form.kraj }}
            </div>
            <button type="submit" class="btn btn-primary">Szukaj</button>
            <h2>Wyniki wyszukiwania:</h2>
        </form>   
    </div>
    <ul>
        {% for klub in kluby %}
            <div class="card-container">
                <div class="card" style="width: 40rem;">
                    <div class="card-body">
                        <img src="/media/{{ klub.logo }}" alt="" class="logo_fc">
                        <div class="row">
    
                            <div class="col-9">
                                <h5 class="card-title">{{ klub }}</h5>
                            </div>
                            <div class="col-3">
                                <a href="{% url 'edytuj_fc' klub.id %}"><i class="fa-solid fa-2x fa-pen-to-square"></i></a>
                                <a href="{% url 'usun_fc' klub.id %}"><i class="fa-solid fa-2x fa-trash"></i></a>
                            </div>
                        </div>
                        <div class="row">
                            <p class="card-text">{{ klub.opis }}</p>
                            <p class="card-text">Kraj: {{ klub.get_kraj_display }}</p>
                        </div>
    
                    </div>
                </div>
            </div>
        {% empty %}
            <li>Brak wyników.</li>
        {% endfor %}
    </ul>
    <div class="hero-shadow"></div>
</header>
{% endblock %}





